import { readFileSync, existsSync } from "fs";
import { join } from "path";
import { loadRegistry } from "./registry.js";

/** Regex to detect YAML frontmatter delimited by --- */
const FRONTMATTER_RE = /^---\n([\s\S]*?)\n---\n/;

export interface AdaptationResult {
  /** The adapted markdown / yaml+markdown content. */
  content: string;
  /** Relative path where this file should be written. */
  target_file: string;
  /** Format hint: "markdown" or "yaml+markdown". */
  format: string;
  /** When true, content should be appended to an existing file. */
  append?: boolean;
}

/**
 * Extract YAML frontmatter (the block between --- delimiters) and the body.
 * Returns { frontmatter: string | null, body: string }.
 */
function parseFrontmatter(raw: string): { frontmatter: string | null; body: string } {
  const match = raw.match(FRONTMATTER_RE);
  if (match) {
    return {
      frontmatter: match[1].trim(),
      body: raw.slice(match[0].length).trim(),
    };
  }
  return { frontmatter: null, body: raw.trim() };
}

/**
 * Generate a URL-safe slug from an agent name.
 */
function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * Read SKILL.md from an agent directory and adapt it for the target tool.
 *
 * @param agentPath - Path to the agent directory (must contain SKILL.md).
 * @param target    - Registry key of the target tool (e.g. "opencode").
 * @returns AdaptationResult with the transformed content and target path.
 */
export function adaptAgent(agentPath: string, target: string): AdaptationResult {
  const skillPath = join(agentPath, "SKILL.md");
  if (!existsSync(skillPath)) {
    throw new Error(`SKILL.md not found in agent directory: ${agentPath}`);
  }

  const raw = readFileSync(skillPath, "utf8");
  const { frontmatter, body } = parseFrontmatter(raw);

  // Derive the agent name from the directory name
  const agentName = agentPath.split("/").pop() || "agent";
  const slug = slugify(agentName);

  const registry = loadRegistry();
  const toolConfig = registry.tools[target];
  if (!toolConfig) {
    return { content: `# Error

Unknown target tool: ${target}`, target_file: `unknown/${target}.md`, format: "markdown", error: `Unknown target tool: ${target}` };
  }

  switch (target) {
    case "opencode":
    case "cursor": {
      // Strip YAML frontmatter, wrap as a markdown command.
      const header = `# ${agentName}\n\n`;
      return {
        content: header + body,
        target_file: `.${target}/commands/${slug}.md`,
        format: "markdown",
      };
    }

    case "codebuddy": {
      // Keep YAML frontmatter, add codebuddy-specific header.
      let out = "";
      if (frontmatter) {
        out += `---\n${frontmatter}\n---\n\n`;
      }
      out += `<!-- codebuddy:skill name="${agentName}" -->\n\n`;
      out += body;
      return {
        content: out,
        target_file: `.codebuddy/skills/${slug}/SKILL.md`,
        format: "yaml+markdown",
      };
    }

    case "claude_code": {
      // Strip YAML, wrap with slash-command format.
      const ccContent = `# /${slug} — ${agentName}\n\n## Description\n\n${body}`;
      return {
        content: ccContent,
        target_file: `.claude/commands/${slug}.md`,
        format: "markdown",
      };
    }

    case "github_copilot": {
      // Markdown with an agent-style prompt header.
      const ghContent = `# ${agentName}\n\n> AI agent prompt – generated by agent-deploy\n\n${body}`;
      return {
        content: ghContent,
        target_file: `.github/agents/${slug}.md`,
        format: "markdown",
      };
    }

    case "windsurf":
    case "trae": {
      // Rules-style format — add a small header block.
      const rulesContent = `# Rule: ${agentName}\n\n${body}`;
      const dir = `.${target}/rules`;
      return {
        content: rulesContent,
        target_file: `${dir}/${slug}.md`,
        format: "markdown",
      };
    }

    case "aider": {
      // Append-mode: CONVENTIONS.md section.
      const aiderSection = `\n\n---\n## ${agentName}\n\n${body}`;
      return {
        content: aiderSection,
        target_file: "CONVENTIONS.md",
        format: "markdown",
        append: true,
      };
    }

    case "agents_md": {
      // Append-mode: AGENTS.md section.
      const agentsSection = `\n\n---\n## ${agentName}\n\n${body}`;
      return {
        content: agentsSection,
        target_file: "AGENTS.md",
        format: "markdown",
        append: true,
      };
    }

    default:
      throw new Error(`No adaptation strategy for tool: ${target}`);
  }
}
